sudo: required
language: go

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y zookeeper zookeeperd

go:
  - 1.4
  - 1.5
install:
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get github.com/tools/godep
  - go get -u github.com/golang/protobuf/proto
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get github.com/gogo/protobuf/protoc-gen-gogo
  - mkdir -p $GOPATH/src/github.com/mesos && git clone https://github.com/mesos/mesos-go.git $GOPATH/src/github.com/mesos/mesos-go
  - cd $GOPATH/src/github.com/mesos/mesos-go/mesosproto && make
before_script:
  - sudo /etc/init.d/zookeeper start
script:
  - TAGS=dev make
  - go test -v=true ./...
